### PR TITLE
Creating travis config to build both boxes with packer.

### PR DESCRIPTION
**Pull request by Tzrlk**
* The ATLAS_TOKEN will need to be encrypted using travis
* I haven't tested the deployment script (I don't know what the packer outputs are).

### CODE REVIEW

**Comment by zimbatm** [comment]
Doesn't atlas support the github integration itself ?

**Comment by zimbatm** [comment]
Just checked, atlas offers integration but wants full admin rights on public and private repos

**Comment by zimbatm** [comment]
@Tzrlk sorry for the wait, I am still pondering on what the best approach is.

Right now Atlas only works for the x86_64 arch for some reason so I still have to build the other box by hand anyways and running `packer push file.json` is not too much of a hassle.

What would be nice is to have PR automatically validate some of the structure of the project like the .json format and make sure the Makefile has been run.

**Comment by Tzrlk** [comment]
Does the Atlas integration support building pull requests? That's the main
benefit I see from using travis. It'll actually give you build status
notifications.

**Comment by zimbatm** [comment]
Answering with another question: is it possible to run the builds without
uploading the artifacts ? I don't want PRs to replace existing images.

Atlas requires too many permissions that I feel comfortable to attach to my
account.

**Comment by Tzrlk** [comment]
Yeah, that's the idea. It only deploys on tags.

**Comment by zimbatm** [comment]
Hey, sorry for not keeping-up on that.

I  just setup the Atlas integration so Travis is not needed. I'll go ahead and close the issue but feel free to comment and I'll re-open it if you think this should still be tackled.

**Pull request closed without merging**
