### PR TITLE
Rename ssh_key_path for packer >0.9

### PR DESCRIPTION
**Pull request by PierreR**

### CODE REVIEW

**Comment by zimbatm** [comment]
Thanks!

**Comment by PierreR** [comment]
Wooah you have been too quick for me ... I have just assumed it was not merged and force a new commit where I change both file and template ...

**Comment by PierreR** [comment]
I am going to change the template in another commit ;-)

**Comment by zimbatm** [comment]
Don't worry, I fixed it on master

**Comment by PierreR** [comment]
Ok I will push a new change that update to 16.03 shortly

**Comment by zimbatm** [comment]
Alright :) 16.09 is also coming out in a couple of days if you're interested

**Comment by PierreR** [comment]
Good news ! I will surely try the new 16.09 as soon as it is out.

By the way, what would be the best  convenient way to make a json for user that are not registered in Atlas ? Currently I manually remove the `atlas` post-processor.

**Comment by zimbatm** [comment]
Yeah that's the best option for now. I think the whole system is a bit upside down and should be refactored so that get_iso_urls.rb generates a JSON file that contains all the ISO url information, and then a single script would generate both packer .json from that file and the ruby template.

**Pull request merged**
